# Generated by Django 4.2.7 on 2023-11-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('upload_date', models.DateField()),
                ('exchange_date', models.DateField(primary_key=True, serialize=False)),
                ('base_currency', models.CharField(max_length=3)),
                ('usd_rate', models.FloatField()),
                ('gbp_rate', models.FloatField()),
                ('ron_rate', models.FloatField()),
            ],
        ),
    ]
