# Generated by Django 4.2.7 on 2023-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exchangerate',
            table='exchange_rates',
        ),
    ]
